---
# Confluence varibales

# docker image version
app_docker_image:           '6.14.1'

app_docker_postgres_image:  '{{ docker_default_postgres_image }}'
app_docker_mysql_image:     '{{ docker_default_mysql_image }}'

# Enable/disable auto container updates via watchtower
app_watchtower:             'false'
app_db_watchtower:          'false'

# data dir
app_base_dir:               '{{ selfhosted_base_dir }}/{{ app_name }}'
app_data_dir:               '{{ app_base_dir }}/data'
app_datadump_dir:           '{{ app_base_dir }}/database_dump'

# database settings (choose one)
#app_db_type:               'mysql'        # (MariaDB) !!! not yet working !!!
app_db_type:                'pgsql'        # (PostgreSQL)

app_database_initdb_args:   '--encoding=UTF-8 --lc-collate=UTF-8 --locale=de_DE.UTF-8'

# options for mariadb or postgres
app_db_name:                'confluence'
app_db_user:                'confluence'
app_db_passwd:              ''              # leave empty to generate random password
