---
# create all diretories

- name: make sure {{ app_base_dir }} is present
  file:
    name: '{{ app_base_dir }}'
    owner: 'root'
    group: 'root'
    mode:  '0700'
    state: 'directory'

- name: make sure wallabag directoies are present
  file:
    name:  '{{ item }}'
    mode:  '0700'
    owner: '65534'
    group: '65534'
    state: 'directory'
  loop:
    - '{{ app_data_dir }}'
    - '{{ app_images_dir }}'
    - '{{ app_datadump_dir }}'
  when: item.startswith("/")
  
- name: configure selinux if needed
  include_tasks: tasks\selinux_docker_dirs.yml
  when:
    - ('status' in ansible_selinux)
    - (ansible_selinux.status == "enabled")
