---
# tasks file to start grav container

- name: '{{ app_name }} | create grav container'
  docker_container:
    name:           '{{ app_name }}'
    image:          'yobasystems/alpine-grav:{{ app_docker_image }}'
    restart_policy: 'unless-stopped'
    networks:       [ name: '{{ app_name }}' ]
    purge_networks: true
    volumes:        '{{ app_docker_vol }}'
    env:            '{{ app_docker_env }}'
    labels:         '{{ app_docker_labels }}'
    state:          'started'
