---
# tasks file to start rocketchat container

- name: '{{ app_name }} | create rocketchat container'
  docker_container:
    name:           '{{ app_name }}'
    image:          'rocketchat/rocket.chat:{{ app_docker_image }}'
    restart_policy: 'unless-stopped'
    links:          '{{ app_name }}-db:rocketchat-mongo'
    networks:       [ name: '{{ app_name }}' ]
    purge_networks: true
    volumes:        '{{ app_docker_vol }}'
    env:            '{{ app_docker_env }}'
    labels:         '{{ app_docker_labels }}'
    state:          'started'
