---

- name: make sure {{ selfhosted_base_dir }} is present
  file:
    name: "{{ selfhosted_base_dir }}"
    owner: "{{ ansible_env.SUDO_USER | default('root') }}"
    group: "{{ ansible_env.SUDO_USER | default('root') }}"
    state: directory

- name: make sure {{ selfhosted_credential_store }} is present
  file: 
    name: '{{ selfhosted_credential_store }}'
    owner: "{{ ansible_env.SUDO_USER | default('root') }}"
    group: "{{ ansible_env.SUDO_USER | default('root') }}"
    mode:  0700
    state: directory
