---
# tasks file for prepare_os

- name: include os specific tasks
  include_tasks: "{{ ansible_distribution }}.yml"

- name: include os tuning tasks
  include_tasks: tuning.yml

- name: create base directories
  include_tasks: directory_structure.yml
