---
# tasks file for docker_turnserver
# start all needed base container

- name: '{{ app_name }} | include nextcloud vars'
  include_vars: "{{ item }}"
  loop:
    - group_vars/traefik.yml
    - group_vars/turnserver.yml

- name: '{{ app_name }} | docker turnserver (talk)'
  include_tasks: turnserver.yml

- name: '{{ app_name }} | open firewall (talk)'
  include_tasks: firewall.yml
