---
# tasks file to start adminer container

- name: 'Create adminer container'
  docker_container:
    name:           'adminer'
    image:          'adminer:{{ docker_adminer_image }}'
    restart_policy: 'unless-stopped'
    networks:       [ name: 'frontend' ]
    state:          'started'
    labels:
      traefik.docker.network:                        'frontend'
      traefik.enable:                                'true'
      traefik.frontend.rule:                         'Host:{{ app_server_fqdn }}; PathPrefixStrip:/adminer'
      traefik.port:                                  '8080'
      traefik.protocol:                              'http'
      traefik.frontend.headers.referrerPolicy:       'no-referrer'
      traefik.frontend.headers.SSLRedirect:          'true'
      traefik.frontend.headers.STSSeconds:           '315360000'
      traefik.frontend.headers.browserXSSFilter:     'true'
      traefik.frontend.headers.contentTypeNosniff:   'true'
      traefik.frontend.headers.forceSTSHeader:       'true'
      traefik.frontend.headers.STSIncludeSubdomains: 'true'
      traefik.frontend.headers.STSPreload:           'true'
      traefik.frontend.headers.frameDeny:            'true'
      com.centurylinklabs.watchtower.enable:         '{{ watchtower_adminer }}'
